# Generated by Django 5.2.6 on 2025-09-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_attendance_student_delete_table_attendance_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_rollno',
            field=models.CharField(default='TEMP', max_length=20, unique=True),
        ),
    ]
