# Generated by Django 5.2.6 on 2025-09-19 06:17

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_student_student_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_image',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to=myapp.models.student_images_path),
        ),
    ]
