# Generated by Django 5.2.6 on 2025-09-19 13:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_attendance_student_image_attendance_student_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
