# Generated by Django 5.2.6 on 2025-09-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_attendance_date_alter_attendance_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_image',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='dataset/'),
        ),
    ]
